### ISSUE TITLE
error installing plugin in ghidra 11.0.1

### ISSUE THREAD

**Issue by lockbox** [fmagin/ghidra-kotlin-extension-template#1]
When attempting to install the plugin using the bare template ghidra *can* successfully add the plugin to the `$GHIDRA_HOME/.ghidra<version>/Extensions/` folder and list it as available. But when you attempt to install the plugin you get the following error message.

<html>
<body>

2024-03-10 | 13:46:24 | ERROR | (ExtensionTableModel) Unable install an extension that no longer exists. Restart Ghidra and try manually installing the extension: 'upstream-template'
-- | -- | -- | --

</body>
</html>

(`upstream-template` is the folder that the `ghidra-kotlin-extension-template` was cloned into).

I'm not entirely sure what going on as i havent debugged this at all, but would appreciate some advice on how to either solve or track this down since i would 100% rather write kotlin that java.

**Comment by lockbox** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra%2FFramework%2FProject%2Fsrc%2Fmain%2Fjava%2Fghidra%2Fframework%2Fproject%2Fextensions%2FExtensionTableModel.java#L166

Saving this here to debug for later

**Comment by lockbox** [comment]
Ah, pretty sure it just needs a `Module.manifest`, will check when I get back to my office

**Comment by fmagin** [comment]
Good catch, thank you very much!

I think I never noticed this because I only used this template repo for extensions I was using in an IDE and never shipped them. IntelliJ adds the classes to the classpath by default which probably bypasses these checks.
